[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-consensus = "0.11.1"
alloy-primitives = "0.8.21"
alloy-rlp = "0.3.11"
alloy-rpc-types  = "0.11.1"
alloy-trie = "0.7.9"
serde = {version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
